import React from 'react';
import {
  BrowserRouter,
  Switch,
  Route,
    Redirect
} from 'react-router-dom';
import {RouteWithLayout} from './../components';
import { Main as MainLayout, Minimal as MinimalLayout } from './../layouts';
import {
    SignUp,
    SignIn,
    UserTable,
    ProfileTable,
    ProfileDetails,
    RedefinePassword,
    ResetPassword,
    CourseTable,
    SkillTable,
    ObjectTable,
    PageNotFound,
    RequestUserTable,
    AccountDetails,
    Dashboard,
    EvaluationTable,
    EvaluationArchiveTable,
    EvaluationDetails,
    SkillDetails,
    ObjectDetails,
    RequestUserDetails,
    CourseDetails,
    UserRequestCourse,
    EvaluationApplicationTable,
    DoEvaluation,
    EvaluationApplicationDetails,
    EvaluationApplicationResults,
    StartEvaluation, EvaluationsResultStudent, EvaluationsResultStudentDetails
} from '../pages';
import UserRequestCourseDetails from "../pages/UserRequestCourse/UserRequestCourseDetails";
import QuestionTable from "../pages/Professor/Question/QuestionTable";
import QuestionDetails from "../pages/Professor/Question/QuestionDetails";

const Routes = () => (
  <BrowserRouter>
    <Switch>
        <Redirect
            exact
            from="/"
            to="/home"
        />
        {/*ROTAS COMUNS*/}
        <RouteWithLayout
          component={Dashboard}
          exact
          needToBeLogged={true}
          layout={MainLayout}
          path="/home"/>
        <RouteWithLayout
            component={SignUp}
            exact
            layout={MinimalLayout}
            needToBeLogged={false}
            path="/sign-up"/>
        <RouteWithLayout
            component={SignIn}
            exact
            layout={MinimalLayout}
            needToBeLogged={false}
            path="/sign-in"/>
        <RouteWithLayout
            component={RedefinePassword}
            exact
            layout={MinimalLayout}
            needToBeLogged={false}
            path="/redefine-password"/>
        <RouteWithLayout
            component={ResetPassword}
            exact
            layout={MinimalLayout}
            needToBeLogged={false}
            path="/reset-password/:token"/>
        <RouteWithLayout
            component={AccountDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/account"/>
        <RouteWithLayout
            component={UserRequestCourse}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/requests"/>
        <RouteWithLayout
            component={UserRequestCourseDetails}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/new-request"/>
        <RouteWithLayout
            component={StartEvaluation}
            exact
            layout={MinimalLayout}
            needToBeLogged={true}
            path="/student/start-evaluation"/>
        <RouteWithLayout
            component={EvaluationsResultStudent}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/student/result-evaluations"/>
        <RouteWithLayout
            component={EvaluationsResultStudentDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/student/result-evaluations/details/:idHead"/>
        {/*ROTAS DO ADMINISTRADOR*/}
        <RouteWithLayout
            component={CourseTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/courses"/>
        <RouteWithLayout
            component={CourseDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/course-details"/>
        <RouteWithLayout
            component={CourseDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/course-details/:codigoCourse"/>
        <RouteWithLayout
            component={ProfileTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/profiles"/>
        <RouteWithLayout
            component={ProfileDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/profile-details"/>
        <RouteWithLayout
            component={ProfileDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/profile-details/:codigoProfile"/>
        <RouteWithLayout
            component={SkillTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/skills"/>
        <RouteWithLayout
            component={SkillDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/skill-details"/>
        <RouteWithLayout
            component={SkillDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/skill-details/:codigoSkill"/>
        <RouteWithLayout
            component={ObjectTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/objects"/>
        <RouteWithLayout
            component={ObjectDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/object-details"/>
        <RouteWithLayout
            component={ObjectDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/object-details/:codigoObject"/>
        <RouteWithLayout
            component={UserTable}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/users"/>
        <RouteWithLayout
            component={RequestUserTable}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/users/requests"/>
        <RouteWithLayout
            component={RequestUserDetails}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/users/requests/:codigoCourseProfessor"/>
        {/*ROTAS DO PROFESSOR*/}
        <RouteWithLayout
            component={EvaluationTable}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/evaluations"/>
        <RouteWithLayout
            component={EvaluationArchiveTable}
            exact
            needToBeLogged={true}
            layout={MainLayout}
            path="/evaluations-archive"/>
        <RouteWithLayout
            component={EvaluationDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/evaluation-details"/>
        <RouteWithLayout
            component={EvaluationDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/evaluation-details/:codigoEvaluation"/>
        <RouteWithLayout
            component={EvaluationApplicationTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/applications-evaluation"/>
        <RouteWithLayout
            component={EvaluationApplicationDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/applications-evaluation/details/:idApplication"/>
        <RouteWithLayout
            component={EvaluationApplicationResults}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/applications-evaluation/results/:idApplication"/>
        <RouteWithLayout
            component={QuestionTable}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/questions"/>
        <RouteWithLayout
            component={QuestionDetails}
            exact
            layout={MainLayout}
            needToBeLogged={true}
            path="/question-details"/>
        <RouteWithLayout
            component={DoEvaluation}
            exact
            layout={MinimalLayout}
            needToBeLogged={true}
            path="/code/:codeAplication"/>
      <RouteWithLayout
          path="*"
          layout={MinimalLayout}
          component={PageNotFound} />
    </Switch>
  </BrowserRouter>
);

export default Routes;
