export { default as PageNotFound } from './PageNotFound';
export { default as Unauthorized } from './Unauthorized';
export { default as AccountDetails } from './AccountDetails';
export { default as UserRequestCourseTable } from './UserRequestCourse/UserRequestCourseTable';
export { default as UserRequestCourseDetails } from './UserRequestCourse/UserRequestCourseDetails';
export { default as Dashboard } from './Dashboard';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as RedefinePassword } from './RedifinePassword';
export { default as ResetPassword } from './ResetPassword';
export { default as UserTable} from './Administrator/UserTable';
export { default as RequestUserTable} from './Administrator/RequestUser/RequestUserTable';
export { default as RequestUserDetails} from './Administrator/RequestUser/RequestUserDetails';
export { default as SkillTable} from './Administrator/Skill/SkillTable';
export { default as SkillDetails} from './Administrator/Skill/SkillDetails';
export { default as ObjectTable} from './Administrator/Object/ObjectTable';
export { default as ObjectDetails} from './Administrator/Object/ObjectDetails';
export { default as CourseTable } from './Administrator/Course/CourseTable';
export { default as CourseDetails } from './Administrator/Course/CourseDetails';
export { default as ProfileTable } from './Administrator/Profile/ProfileTable';
export { default as ProfileDetails } from './Administrator/Profile/ProfileDetails';
export { default as EvaluationTable } from './Professor/Evaluation/EvaluationTable';
export { default as EvaluationArchiveTable } from './Professor/Evaluation/EvaluationArchiveTable';
export { default as EvaluationDetails } from './Professor/Evaluation/EvaluationDetails';
export { default as EvaluationApplicationTable } from './Professor/EvaluationApplication/EvaluationApplicationTable';
export { default as EvaluationApplicationDetails } from './Professor/EvaluationApplication/EvaluationApplicationDetails';
export { default as EvaluationApplicationResults } from './Professor/EvaluationApplication/EvaluationApplicationResults';
export { default as DoEvaluation } from './Student/DoEvaluation';
export { default as StartEvaluation } from './Student/StartEvaluation';
export { default as EvaluationsResultStudent } from './Student/EvaluationsResult/EvaluationsResultTable/EvaluationsResultStudentTable';
export { default as EvaluationsResultStudentDetails } from './Student/EvaluationsResult/EvaluationResultDetails/EvaluationsResultDetails';
