export { default as PageNotFound } from './PageNotFound';
export { default as AccountDetails } from './AccountDetails';
export { default as Dashboard } from './Dashboard';
export { default as SignIn } from './SignIn';
export { default as SignUp } from './SignUp';
export { default as RedefinePassword } from './RedifinePassword';
export { default as ResetPassword } from './ResetPassword';
export { default as UserTable} from './Administrator/UserTable';
export { default as RequestUserTable} from './Administrator/RequestUser/RequestUserTable';
export { default as SkillTable} from './Administrator/Skill/SkillTable';
export { default as ObjectTable} from './Administrator/Object/ObjectTable';
export { default as CourseTable } from './Administrator/Course/CourseTable';
export { default as ProfileTable } from './Administrator/Profile/ProfileTable';
export { default as ProfileDetails } from './Administrator/Profile/ProfileDetails';
export { default as EvaluationTable } from './Professor/Evaluation/EvaluationTable';
export { default as EvaluationArchiveTable } from './Professor/Evaluation/EvaluationArchiveTable';
